version: "3"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    restart: always
    ports:
      - "9411:9411"
  db:
    image: 'postgres:15.1'
    container_name: db
    environment:
      - POSTGRES_USER=whisky
      - POSTGRES_PASSWORD=whisky
    ports:
      - "5432:5432"