spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/whisky
    username: whisky
    password: whisky

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.data: DEBUG
